apiVersion: v1
data:
  app_name: hey-there # This is a test configmap
  app_env: test-env
  log_level: error
kind: ConfigMap
metadata:
  annotations:
    strategy.spinnaker.io/versioned: "false"
  namespace: ns-prod