apiVersion: v1
data:
  app_name: hey-there4 # This is a test configmap
  app_env: test-env
  log_level: debug
kind: ConfigMap
metadata:
  annotations:
    strategy.spinnaker.io/versioned: "false"
  name: testconfigmap
  namespace: ns-prod